### ISSUE TITLE
Only crawling 2 links

### ISSUE THREAD

**Issue by dualaudi** [nazuke/SEOMacroscope#12]
I can't seem to crawl more than 2 links. I feel like it's a default setting, but I've adjusted the settings and it still does not crawl/report more than root and robots, or root, robots, and xml links. What am I doing wrong?

Edit. I've downloaded ver 1.5 and it's working - i will retest with 1.6.

**Comment by dualaudi** [comment]
Follow up, I've tested 16.0.0 thoroughly with a lot of different settings and it wont' crawl past index/robots/sitemap. Version 15.0.0 seems to crawl just fine. On a x64 win10 32gb ram, i7-3770

**Comment by nazuke** [comment]
Hi Dualaudi, and thank you for your interest in SEO Macroscope.

You've very likely uncovered a bug.

Firstly, this may be a problem with the application's current lack of support for HTTP/2. In which case, it would either not crawl at all, or bail out at the first page or so. I am currently working on the HTTP/2 issues in the 1.7 branch; but there are a lot of changes, so it'll take a while.

However, this may also be due to the URL you entered as being different to the rest of your site. For example, if you entered:

    https://company.com/

...but your site normally has internal links, or redirects that refer to itself as:

    https://www.company.com/

...then it will halt crawling, as the other link variants will be considered "external".

In this case, you're probably seeing it crawl something like:

    https://company.com/robots.txt

    https://company.com/

...and then stopping.

Do you mind if I ask what the URL was that you were trying to crawl please? And, could I have your permission to try some test crawls?

many thanks
