### ISSUE TITLE
Problem to check domain https

### ISSUE THREAD

**Issue by cworldonline** [nazuke/SEOMacroscope#14]
I have 3 domain con redirect http to https
but if i check https://www.example.it, with this prog i see:
https://www.example.it redirect 301 to https://www.example.it

i do other check with httpstatus.io and all is ok

Help me
Thanks

**Comment by nazuke** [comment]
Many thanks for your interest in SEO Macroscope cworldonline.

This may be a bug in v1.6. I'm just going to try a handful of initial scans of that problem with the v1.7 branch. And will follow up shortly.

**Comment by nazuke** [comment]
OK, the first thing is that the SSL certificate on the https://www.example.it site is invalid. It looks like you're using a development SSL certificate?

This can be overridden by unchecking:

> Edit -> Preferences -> Network Settings -> Server Certificates -> Enable certificate validation

Next, your robots.txt is disallowing the entire site from being crawled:

    User-agent: *
    Disallow: /

If you turn off *Follow robots protocol* in the preferences, then those rules will be ignored.

You can see which URLs get blocked under the *Robots* tab when the crawl has completed.

In the v.17 branch, I've added a new Robots column to the Structure Overview tab, as it's still a little confusing to see when things are being blocked or not due to robots rules.

With the above, I can see that you're example site is a WP site, it mostly looks like only the login page is reachable.

You may also need to enable *Follow redirects* in preferences, if there are any instances where you're site jumps from the HTTPS to the non-HTTPS version.

Many thanks for your feedback!
