### ISSUE TITLE
Error saving sitemap XML

### ISSUE THREAD

**Issue by ilitur** [nazuke/SEOMacroscope#19]
there's an error exporting sitemap xml from file menu.
![immagine](https://user-images.githubusercontent.com/37334704/37341342-59e2d79c-26c1-11e8-9694-c71a1ce165be.png)
SEO Macroscope Version 1.6 and Version 1.7

**Comment by nazuke** [comment]
Thank you very much for reporting this @ilitur, I am investigating this issue very shortly.

**Comment by nazuke** [comment]
Hi @ilitur ,

OK, it looks like the error is reproducible when attempting to save a sitemap *before* making a scan.

Can I ask, did you perform a scan from a URL pasted into the **Start URL** field, or did you do a list scan with one of the **File -> Load URL List** commands?

If it is the former, could I ask what the URL was please?

The bug appears to be a result of the Start URL being either missing or changed for some reason since it was entered, with the result that the "start document" inside the application not being found when the sitemap generator tries to use it. It's definitely a bug.

**Comment by ilitur** [comment]
Hi,

I made a scan before the export... as you can see in the screenshot, the background table is about a scan made by the **Start URL** field
I've tryed with three differents url, so I think that the problem isn't the website but the software.

![image](https://user-images.githubusercontent.com/37334704/37455848-5fb01ac6-283e-11e8-9732-b4601104f0e9.png)

![image](https://user-images.githubusercontent.com/37334704/37455869-6a9d1b50-283e-11e8-9f40-20ca5ea741a2.png)

![image](https://user-images.githubusercontent.com/37334704/37455896-7975dcfc-283e-11e8-96f2-df458a365f56.png)

![image](https://user-images.githubusercontent.com/37334704/37455911-81e47cfe-283e-11e8-914f-614713e6168f.png)

**Comment by nazuke** [comment]
Noting URL for later reference: http://www.corsidiscultura.it/

**Comment by nazuke** [comment]
Looking at this more recently, this bug appears to have been fixed. Cannot reproduce currently.
