### ISSUE TITLE
404 link not found?

### ISSUE THREAD

**Issue by semperaye** [nazuke/SEOMacroscope#22]
Hello. I'm not sure if I'm using the program correctly, or if this is a bug. Let me explain....

I can seem to be able to find 404's when searching by root domain, but when I try to find 404's on a particular page, nothing is found. I created a test page so I could test this, there is a 404 link on that page but I can't get SEOMacroscope to find it unless I scan my entire website. Is there a way to scan pages alone? I would love to be able to scan large lists of pages without having to scan the entire domain. Maybe its something in my settings? I have page deph set to 1 at the moment, but I've tried a few other settings without luck. Any help would be awesome. I really love this program its epic at scanning the root domains, but thats not really what I need it for.

https://www.salamatphilippines.com/404-test-page/

**Comment by nazuke** [comment]
Many thanks for this feedback @semperaye, this is very useful.

I just tried your use case, and I think I can see what's happening here.

The link on the page you give is on a different website to the original. By default, SEO Macroscope will class this as an "external host", there are some notes on it here:

> https://nazuke.github.io/SEOMacroscope/manual/#internal-and-external-hosts

However, you *should* eventually see that being reported as a 404 page. But it may take some time, as it is also crawling the rest of the web site.

If you have a list of URLs that you want to very quickly check, please use one of the:

> File -> Load URL List

...commands, and load or paste in a list of URL to check. These can be on different websites. These exact URLs will only be checked, unless:

> Edit -> Preferences -> Analysis Options -> List File Processing -> Scan sites in list

...is switched on.

I just ran a short scan of your site, using:

> https://www.salamatphilippines.com/404-test-page/

...as a starting point. And I do see the example 404 page turning up as a 404, along with a number of others.

If you'd like to simply check your web pages quickly, then I'd recommend switching off the CSS, JS, and other document types in:

> Preferences -> Crawl Link Types

...this will speed things up a little, and make fewer requests. HTML pages are *always* crawled.

Also, your site just revealed a bug in the sitemap processing, which will be fixed in the next release; so thanks again for reporting this, it helps a lot! :-)

**Comment by nazuke** [comment]
@semperaye, please note, I will be moving the:

> Edit -> Preferences -> Analysis Options -> List File Processing -> Scan sites in list

...option to the "Spidering Control" tab in the next release.

**Comment by semperaye** [comment]
Maybe what I need to do is select "Check external links," then tweak the max page depth to 1. The max pages to fetch, is that pages on a domain, or total of all pages?

**Comment by semperaye** [comment]
It appears there is an issue with page deph
