### ISSUE TITLE
Insufficient memory available

### ISSUE THREAD

**Issue by ekussberg** [nazuke/SEOMacroscope#4]
![image](https://user-images.githubusercontent.com/5912520/27794239-9bd4f1e4-6001-11e7-9547-6ed10d9287a8.png)

Hi,

i get this error when i try to export the overview. Is there a fix for that?

**Comment by nazuke** [comment]
Thank you for your feedback Ekussberg,

That's a tricky one, I'm afraid. What is happening here is that I'm trying to prevent an actual RAM exhaustion scenario, by checking how much memory we actually have available.

There have been many changes around this area since the last release; including trying to use less RAM for certain operations like this. I will also be adding a preferences option to disable RAM checking before some operations; obviously with the risk that we may actually run out of memory.

For now, please try the following:

1. Go to **Edit**->**Preferences**
1. Click the **Analysis Options** tab
1. Uncheck **Enable Levenshtein duplicate detection**
1. Retry

Also, scanning smaller sections of the site may avoid this problem.

I'm working towards a new release, but may produce an interim release shortly, time permitting. If you are comfortable doing so, it is also possible to build from the source directly.

Thank you for your interest in SEO Macroscope,

Jason

**Comment by nazuke** [comment]
On 64 bit builds, this issue should now be resolved.
